[workspace]
resolver = "2"
members = [
  "crates/store", "node", ]

exclude = [
"bitcoin-wasm",
   "lightning-wasm",
  "wallet","crates/tbdex", "tests/artifacts", "tests/runner", "examples/mobile-money"
]
