[workspace]
resolver = "2"
members = [
  "crates/store", "node", "crates/tbdex", "tests/artifacts", "tests/runner", "examples/mobile-money"]

exclude = [
"bitcoin-wasm",
   "lightning-wasm",
  "wallet",
]
